const {
  VITE_APP_URL,
  VITE_APP_API,
  VITE_APP_STATIC,
  VITE_APP_LOG,
  VITE_APP_LOGIN_EMAIL,
  VITE_APP_LOGIN_PASSWORD,
  MODE
} = import.meta.env;
export {
  VITE_APP_URL,
  VITE_APP_API,
  VITE_APP_STATIC,
  VITE_APP_LOG,
  VITE_APP_LOGIN_EMAIL,
  VITE_APP_LOGIN_PASSWORD,
  MODE
};
